theme: jekyll-theme-cayman
title: "WBZ A parallel implementation of the bzip2 data compressor in python "
description: "A parallel implementation of the bzip2 data compressor in python, this data compression pipeline is using algorithms like Burrows–Wheeler transform (BWT) and Move to front (MTF) to improve the Huffman compression. For now, this tool only will be focused on compressing .csv files and other files on tabular format."
author: "Ramses Alexander Coraspe Valdez"
